# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20191124_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
