# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/smoke.jpeg', upload_to='images/'),
        ),
    ]
